### ISSUE TITLE
Only produce Github action output for cases that result in exitCode > 0

### ISSUE THREAD

**Issue by icanhazstring** [composer-unused/composer-unused#399]
## Describe the bug
Right now, it happens that ignored packages are actually emitting a `warning` log state for `composer.json` when a package is being ignored while running a github action.

This should not happen, as ignore packages do not count towards an exitCode > 0.
https://github.com/composer-unused/composer-unused/blob/main/src/OutputFormatter/GithubFormatter.php#L57

## TODO
- [x] simple log message that this package was ignored
- [x] no link to `composer.json` about a warning
- [x] the message should be `a/b was ignored` instead of `is invalid`
- [x] add tests

**Comment by icanhazstring** [comment]
Ref #397

**Comment by ayushthe1** [comment]
Hey ,i would like to contribute to this issue but currently im a beginner to open-source and don't know anything about github actions .Could you please guide me to solving this issue ,if u think its possible for me to do at this stage.

**Comment by icanhazstring** [comment]
Hi @ayushthe1 welcome aboard :)
Let me give you some hints what needs to be done:

1. The message here should be `%s was ignored` https://github.com/composer-unused/composer-unused/blob/main/src/OutputFormatter/GithubFormatter.php#L56
2. There should be no `::warning` in front of the message itself, so it just gets written out into the log https://github.com/composer-unused/composer-unused/blob/main/src/OutputFormatter/GithubFormatter.php#L57
3. A new unit test here https://github.com/composer-unused/composer-unused/tree/main/tests/Unit/OutputFormatter `GithubFormatterTest` should be added. You can get an idea how to do this from the `JsonFormatterTest`

**Comment by ayushthe1** [comment]
> Hi @ayushthe1 welcome aboard :) Let me give you some hints what needs to be done:
> 
> 1. The message here should be `%s was ignored` https://github.com/composer-unused/composer-unused/blob/main/src/OutputFormatter/GithubFormatter.php#L56
> 2. There should be no `::warning` in front of the message itself, so it just gets written out into the log https://github.com/composer-unused/composer-unused/blob/main/src/OutputFormatter/GithubFormatter.php#L57
> 3. A new unit test here https://github.com/composer-unused/composer-unused/tree/main/tests/Unit/OutputFormatter `GithubFormatterTest` should be added. You can get an idea how to do this from the `JsonFormatterTest`. You will test that the message has the correct information (e.g. without `::warning`)
> 
> You can start working and open a PR as a draft as soon as possible. This way I can support you if you have further questions.

Thanks ,i will look into all the resources you provided.

**Comment by ayushthe1** [comment]
@icanhazstring Hey i fixed the first 2 points that you mentioned and also created a directory `GithubFormatterTest` directory in `OutputFormatter` directory . But i dont know how to write unit tests ,could you please help me with it .

**Comment by icanhazstring** [comment]
Sure thing.

You can take a look at the test here:
https://github.com/composer-unused/composer-unused/blob/main/tests/Unit/OutputFormatter/JsonFormatter/JsonFormatterTest.php

What you need to do, is to
1. Create the service you want to test, in this case the `GithubFormatter`
2. You want to create a collection for "ignored packages"
   - for example you can create one using

      ```
      $unusedDependencyCollection = new DependencyCollection([
          new RequiredDependency(new Package('symfony/console'))
      ]);
      ```
    - this one you need to pass into your `GithubFormatter`
    - the others can be mocked using `$this->createMock(DependencyCollection::class)`
3. The `$rootPackage` needs to be mocked as well and you need to tell the mock that for a certain
    This can be done using:
    ```
    $link = $this->createMock(LinkInterface::class); // Its the interface from ComposerUnused\Contracts
    $link->method('getLineNumber')->willReturn(1); // The line number is part of the output

    $rootPackage = $this->createMock(PackageInterface::class); // Also from ComposerUnused\Contracts
    $rootPackage
        ->method('<method to be mocked>')
        ->with('<package name>') // this is the package name you previously created
        ->willReturn($link);
    ```

    Passing in that `$rootPackage` should help you get the correct output when calling `->formatOutput` on you `GithubFormatter` instance.

I hope3t helps. I left out some information for you to figure out.
If you need more help let me know 👍

**Comment by ayushthe1** [comment]
Thanks ,i will look into this.

**Comment by lptn** [comment]
thanks, agree, it's annoying to see ignored dependencies on github actions output and as GitHub code annotations: 

<img width="823" alt="image" src="https://user-images.githubusercontent.com/5278175/195343906-3b5f9aca-d7ff-4fa9-a1f8-714b9e46366f.png">

<img width="525" alt="image" src="https://user-images.githubusercontent.com/5278175/195344066-5015bbae-124f-4f5f-9ef7-6bff89e8eca1.png">

**Comment by ayushthe1** [comment]
Hey @icanhazstring ,i made another PR for this issue with unit tests . Could you please review it.
Sorry for submitting it late.
